### ISSUE TITLE
More Examples and Docs

### ISSUE THREAD

**Issue by tsantero** [andrewjstone/amy#7]
while the two tests in the repo help a bit, amy is nonetheless an opinionated library and more example usage and documentation would certainly help (at least my) understanding and adoption on how best to incorporate amy into one of my projects. 

mind you, this request is also coming from a fairly new rust programmer, and so my inability to completely wrap my head around amy's best practices might be a side-affect of inexperience. 

thoughts, @andrewjstone ? 😀

**Comment by andrewjstone** [comment]
@tsantero You are right. It needs more examples. Additionally, I need to fix the broken rustdoc links.

**Comment by andrewjstone** [comment]
Added a [Getting Started Guide](https://github.com/andrewjstone/amy/blob/master/doc/getting_started.md)
